-- WARNING: This will delete the existing database.
-- MySQL Script generated by MySQL Workbench
-- Sun Feb 26 14:58:50 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema estore
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `estore` ;

-- -----------------------------------------------------
-- Schema estore
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `estore` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
SHOW WARNINGS;
USE `estore` ;

-- -----------------------------------------------------
-- Table `estore`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estore`.`address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `address_id` VARCHAR(50) NOT NULL,
  `street_number` VARCHAR(50) NOT NULL,
  `city` VARCHAR(50) NOT NULL,
  `region` VARCHAR(50) NOT NULL,
  `country` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE,
  UNIQUE INDEX `address_id` (`address_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `estore`.`admin_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estore`.`admin_type` (
  `id` INT NOT NULL,
  `admin_type_id` VARCHAR(50) NOT NULL,
  `permission` VARCHAR(50) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE,
  UNIQUE INDEX `admin_type_id` (`admin_type_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `estore`.`system_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estore`.`system_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `system_user_id` VARCHAR(50) NOT NULL,
  `firstname` VARCHAR(50) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE,
  UNIQUE INDEX `system_user_id` (`system_user_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `estore`.`admin_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estore`.`admin_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `admin_user_id` VARCHAR(50) NOT NULL,
  `admin_type_id` VARCHAR(50) NOT NULL,
  `system_user_id` VARCHAR(50) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE,
  UNIQUE INDEX `admin_user_id` (`admin_user_id` ASC) VISIBLE,
  INDEX `FK_admin_type` (`admin_type_id` ASC) VISIBLE,
  INDEX `FK_admin_system_user` (`system_user_id` ASC) VISIBLE,
  CONSTRAINT `FK_admin_system_user`
    FOREIGN KEY (`system_user_id`)
    REFERENCES `estore`.`system_user` (`system_user_id`),
  CONSTRAINT `FK_admin_type`
    FOREIGN KEY (`admin_type_id`)
    REFERENCES `estore`.`admin_type` (`admin_type_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `estore`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estore`.`cart` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cart_id` VARCHAR(50) NOT NULL,
  `name` VARCHAR(50) NULL DEFAULT 'Items',
  `system_user_id` VARCHAR(50) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE,
  UNIQUE INDEX `cart_id` (`cart_id` ASC) VISIBLE,
  INDEX `FK_cart_system_user` (`system_user_id` ASC) VISIBLE,
  CONSTRAINT `FK_cart_system_user`
    FOREIGN KEY (`system_user_id`)
    REFERENCES `estore`.`system_user` (`system_user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `estore`.`vendor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estore`.`vendor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `vendor_id` VARCHAR(50) NOT NULL,
  `system_user_id` VARCHAR(50) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE,
  UNIQUE INDEX `vendor_id` (`vendor_id` ASC) VISIBLE,
  INDEX `FK_vendor_system_user` (`system_user_id` ASC) VISIBLE,
  CONSTRAINT `FK_vendor_system_user`
    FOREIGN KEY (`system_user_id`)
    REFERENCES `estore`.`system_user` (`system_user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `estore`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estore`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category_id` VARCHAR(50) NOT NULL,
  `vendor_id` VARCHAR(50) NULL DEFAULT NULL,
  `admin_user_id` VARCHAR(50) NULL DEFAULT NULL,
  `name` VARCHAR(50) NOT NULL,
  `description` VARCHAR(500) NULL DEFAULT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE,
  UNIQUE INDEX `category_id` (`category_id` ASC) VISIBLE,
  INDEX `FK_vendor_category` (`vendor_id` ASC) VISIBLE,
  INDEX `FK_admin_user_category` (`admin_user_id` ASC) VISIBLE,
  CONSTRAINT `FK_admin_user_category`
    FOREIGN KEY (`admin_user_id`)
    REFERENCES `estore`.`admin_user` (`admin_user_id`),
  CONSTRAINT `FK_vendor_category`
    FOREIGN KEY (`vendor_id`)
    REFERENCES `estore`.`vendor` (`vendor_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `estore`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estore`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_id` VARCHAR(50) NOT NULL,
  `category_id` VARCHAR(50) NOT NULL,
  `system_user_id` VARCHAR(50) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `description` TEXT NOT NULL,
  `price` DECIMAL(10,0) NOT NULL,
  `stock` SMALLINT NOT NULL DEFAULT '1',
  `featured` ENUM('T', 'F') NOT NULL DEFAULT 'F',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE,
  UNIQUE INDEX `product_id` (`product_id` ASC) VISIBLE,
  INDEX `FK_category_product` (`category_id` ASC) VISIBLE,
  INDEX `FK_system_user_product` (`system_user_id` ASC) VISIBLE,
  CONSTRAINT `FK_category_product`
    FOREIGN KEY (`category_id`)
    REFERENCES `estore`.`category` (`category_id`),
  CONSTRAINT `FK_system_user_product`
    FOREIGN KEY (`system_user_id`)
    REFERENCES `estore`.`system_user` (`system_user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `estore`.`shopping_session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estore`.`shopping_session` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `shopping_session_id` VARCHAR(50) NOT NULL,
  `system_user_id` VARCHAR(50) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE,
  UNIQUE INDEX `shopping_session_id` (`shopping_session_id` ASC) VISIBLE,
  INDEX `FK_session_system_user` (`system_user_id` ASC) VISIBLE,
  CONSTRAINT `FK_session_system_user`
    FOREIGN KEY (`system_user_id`)
    REFERENCES `estore`.`system_user` (`system_user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `estore`.`cart_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estore`.`cart_item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cart_item_id` VARCHAR(50) NOT NULL,
  `shopping_session_id` VARCHAR(50) NOT NULL,
  `product_id` VARCHAR(50) NOT NULL,
  `cart_id` VARCHAR(50) NOT NULL,
  `quantity` INT NOT NULL DEFAULT '1',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE,
  UNIQUE INDEX `cart_item_id` (`cart_item_id` ASC) VISIBLE,
  UNIQUE INDEX `product_id` (`product_id` ASC) VISIBLE,
  INDEX `FK_session_cart_item` (`shopping_session_id` ASC) VISIBLE,
  INDEX `FK_product_cart_item` (`product_id` ASC) VISIBLE,
  INDEX `FK_cart_cart_item` (`cart_id` ASC) VISIBLE,
  CONSTRAINT `FK_cart_cart_item`
    FOREIGN KEY (`cart_id`)
    REFERENCES `estore`.`cart` (`cart_id`),
  CONSTRAINT `FK_product_cart_item`
    FOREIGN KEY (`product_id`)
    REFERENCES `estore`.`product` (`product_id`),
  CONSTRAINT `FK_session_cart_item`
    FOREIGN KEY (`shopping_session_id`)
    REFERENCES `estore`.`shopping_session` (`shopping_session_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `estore`.`contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estore`.`contact` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `contact_id` VARCHAR(50) NOT NULL,
  `system_user_id` VARCHAR(50) NOT NULL,
  `phone` VARCHAR(50) NOT NULL,
  `is_primary` ENUM('T', 'F') NOT NULL DEFAULT 'F',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE,
  UNIQUE INDEX `contact_id` (`contact_id` ASC) VISIBLE,
  INDEX `FK_system_user_contact` (`system_user_id` ASC) VISIBLE,
  CONSTRAINT `FK_system_user_contact`
    FOREIGN KEY (`system_user_id`)
    REFERENCES `estore`.`system_user` (`system_user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `estore`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estore`.`location` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `location_id` VARCHAR(50) NOT NULL,
  `system_user_id` VARCHAR(50) NOT NULL,
  `town` VARCHAR(15) NOT NULL,
  `po_box` VARCHAR(20) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE,
  UNIQUE INDEX `location_id` (`location_id` ASC) VISIBLE,
  INDEX `FK_system_user_location` (`system_user_id` ASC) VISIBLE,
  CONSTRAINT `FK_system_user_location`
    FOREIGN KEY (`system_user_id`)
    REFERENCES `estore`.`system_user` (`system_user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `estore`.`onewish`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estore`.`onewish` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `system_user_id` VARCHAR(50) NOT NULL,
  `product_id` VARCHAR(50) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE,
  UNIQUE INDEX `system_user_id` (`system_user_id` ASC) VISIBLE,
  INDEX `FK_product_onewish` (`product_id` ASC) VISIBLE,
  CONSTRAINT `FK_product_onewish`
    FOREIGN KEY (`product_id`)
    REFERENCES `estore`.`productr` (`product_id`),
  CONSTRAINT `FK_system_user_onewish`
    FOREIGN KEY (`system_user_id`)
    REFERENCES `estore`.`system_user` (`system_user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `estore`.`payment_method`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estore`.`payment_method` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `payment_method_id` VARCHAR(50) NOT NULL,
  `admin_user_id` VARCHAR(50) NOT NULL,
  `provider` VARCHAR(50) NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `account_number` VARCHAR(45) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE,
  UNIQUE INDEX `payment_method_id` (`payment_method_id` ASC) VISIBLE,
  INDEX `FK_system_user_payment_method` (`admin_user_id` ASC) VISIBLE,
  CONSTRAINT `FK_system_user_payment_method`
    FOREIGN KEY (`admin_user_id`)
    REFERENCES `estore`.`admin_user` (`admin_user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `estore`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estore`.`payment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `payment_id` VARCHAR(50) NOT NULL,
  `system_user_id` VARCHAR(50) NOT NULL,
  `payment_method_id` VARCHAR(50) NOT NULL,
  `payment_type` ENUM('express', 'regular') NOT NULL DEFAULT 'regular',
  `account_no` VARCHAR(50) NOT NULL,
  `session_id` VARCHAR(50) NOT NULL,
  `order_id` VARCHAR(50) NOT NULL,
  `amount` DECIMAL(15,0) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE,
  UNIQUE INDEX `payment_id` (`payment_id` ASC) VISIBLE,
  INDEX `FK_system_user_payment` (`system_user_id` ASC) VISIBLE,
  INDEX `FK_payment_method_payment` (`payment_method_id` ASC) VISIBLE,
  CONSTRAINT `FK_payment_method_payment`
    FOREIGN KEY (`payment_method_id`)
    REFERENCES `estore`.`payment_method` (`payment_method_id`),
  CONSTRAINT `FK_system_user_payment`
    FOREIGN KEY (`system_user_id`)
    REFERENCES `estore`.`system_user` (`system_user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `estore`.`payment_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estore`.`payment_detail` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `payment_detail_id` VARCHAR(50) NOT NULL,
  `system_user_id` VARCHAR(50) NOT NULL,
  `name` VARCHAR(50) NOT NULL DEFAULT 'MTN MOBILE MONEY',
  `provider` VARCHAR(50) NULL DEFAULT 'MTNCAM',
  `account_number` VARCHAR(50) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE,
  UNIQUE INDEX `payment_detail_id` (`payment_detail_id` ASC) VISIBLE,
  INDEX `FK_system_user_payment_detail` (`system_user_id` ASC) VISIBLE,
  CONSTRAINT `FK_system_user_payment_detail`
    FOREIGN KEY (`system_user_id`)
    REFERENCES `estore`.`system_user` (`system_user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `estore`.`product_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estore`.`product_item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_item_id` VARCHAR(50) NOT NULL,
  `product_id` VARCHAR(50) NOT NULL,
  `product_item_image` LONGBLOB NOT NULL,
  `product_item_price` DECIMAL(10,0) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE,
  UNIQUE INDEX `product_item_id` (`product_item_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `estore`.`product_config`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estore`.`product_config` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_config_id` VARCHAR(50) NOT NULL,
  `product_item_id` VARCHAR(50) NOT NULL,
  `variation_id` VARCHAR(50) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE,
  UNIQUE INDEX `product_config_id` (`product_config_id` ASC) VISIBLE,
  INDEX `FK_product_item_product_config` (`product_item_id` ASC) VISIBLE,
  CONSTRAINT `FK_product_item_product_config`
    FOREIGN KEY (`product_item_id`)
    REFERENCES `estore`.`product_item` (`product_item_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `estore`.`product_image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estore`.`product_image` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_image_id` VARCHAR(50) NOT NULL,
  `product_image` LONGBLOB NOT NULL,
  `product_id` VARCHAR(50) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE,
  UNIQUE INDEX `product_image_id` (`product_image_id` ASC) VISIBLE,
  INDEX `FK_product_product_image` (`product_id` ASC) VISIBLE,
  CONSTRAINT `FK_product_product_image`
    FOREIGN KEY (`product_id`)
    REFERENCES `estore`.`product` (`product_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `estore`.`product_inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estore`.`product_inventory` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `inventory_id` VARCHAR(50) NOT NULL,
  `quantity` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE,
  UNIQUE INDEX `inventory_id` (`inventory_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `estore`.`provider`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estore`.`provider` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `provider_id` VARCHAR(50) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `account_number` VARCHAR(50) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE,
  UNIQUE INDEX `provider_id` (`provider_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `estore`.`review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estore`.`review` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `review_id` VARCHAR(50) NOT NULL,
  `system_user_id` VARCHAR(50) NOT NULL,
  `rating` INT NOT NULL DEFAULT '1',
  `product_id` VARCHAR(50) NOT NULL,
  `comment` VARCHAR(500) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE,
  UNIQUE INDEX `review_id` (`review_id` ASC) VISIBLE,
  INDEX `FK_product_review` (`product_id` ASC) VISIBLE,
  INDEX `FK_system_user_review` (`system_user_id` ASC) VISIBLE,
  CONSTRAINT `FK_product_review`
    FOREIGN KEY (`product_id`)
    REFERENCES `estore`.`product` (`product_id`),
  CONSTRAINT `FK_system_user_review`
    FOREIGN KEY (`system_user_id`)
    REFERENCES `estore`.`system_user` (`system_user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `estore`.`user_image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estore`.`user_image` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_image_id` VARCHAR(50) NOT NULL,
  `nid_recto` LONGBLOB NOT NULL,
  `nid_verso` LONGBLOB NOT NULL,
  `system_user_id` VARCHAR(50) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE,
  UNIQUE INDEX `user_image_id` (`user_image_id` ASC) VISIBLE,
  INDEX `FK_system_user_user_image` (`system_user_id` ASC) VISIBLE,
  CONSTRAINT `FK_system_user_user_image`
    FOREIGN KEY (`system_user_id`)
    REFERENCES `estore`.`system_user` (`system_user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `estore`.`user_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estore`.`user_order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_order_id` VARCHAR(50) NOT NULL,
  `system_user_id` VARCHAR(50) NOT NULL,
  `cart_id` VARCHAR(50) NOT NULL,
  `status` ENUM('payed', 'pending') NOT NULL DEFAULT 'pending',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE,
  UNIQUE INDEX `user_order_id` (`user_order_id` ASC) VISIBLE,
  INDEX `FK_system_user_user_oder` (`system_user_id` ASC) VISIBLE,
  INDEX `FK_cart_user_order` (`cart_id` ASC) VISIBLE,
  CONSTRAINT `FK_cart_user_order`
    FOREIGN KEY (`cart_id`)
    REFERENCES `estore`.`cart` (`cart_id`),
  CONSTRAINT `FK_system_user_user_oder`
    FOREIGN KEY (`system_user_id`)
    REFERENCES `estore`.`system_user` (`system_user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `estore`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estore`.`user_role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_role_id` VARCHAR(50) NOT NULL,
  `name` VARCHAR(25) NOT NULL,
  `description` VARCHAR(50) NULL DEFAULT 'role',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE,
  UNIQUE INDEX `user_role_id` (`user_role_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `estore`.`variation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estore`.`variation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `variation_id` VARCHAR(50) NOT NULL,
  `product_id` VARCHAR(50) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE,
  UNIQUE INDEX `variation_id` (`variation_id` ASC) VISIBLE,
  INDEX `FK_product_variation` (`product_id` ASC) VISIBLE,
  CONSTRAINT `FK_product_variation`
    FOREIGN KEY (`product_id`)
    REFERENCES `estore`.`product` (`product_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `estore`.`variation_option`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estore`.`variation_option` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `variation_option_id` VARCHAR(50) NOT NULL,
  `variation_id` VARCHAR(50) NOT NULL,
  `value` VARCHAR(45) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE,
  UNIQUE INDEX `variation_option_id` (`variation_option_id` ASC) VISIBLE,
  INDEX `FK_variation_variation_option` (`variation_id` ASC) VISIBLE,
  CONSTRAINT `FK_variation_variation_option`
    FOREIGN KEY (`variation_id`)
    REFERENCES `estore`.`variation` (`variation_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `estore`.`verification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estore`.`verification` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `verification_id` VARCHAR(50) NOT NULL,
  `nid_recto` LONGBLOB NOT NULL,
  `nid_verso` LONGBLOB NOT NULL,
  `system_user_id` VARCHAR(50) NOT NULL,
  `status` ENUM('VERIFIED', 'PENDING') NOT NULL DEFAULT 'PENDING',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE,
  UNIQUE INDEX `verification_id` (`verification_id` ASC) VISIBLE,
  INDEX `FK_system_user_id_user_image` (`system_user_id` ASC) VISIBLE,
  CONSTRAINT `FK_system_user_id_user_image`
    FOREIGN KEY (`system_user_id`)
    REFERENCES `estore`.`system_user` (`system_user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
